services:
  myfans-downloader:
#    image: frequency2098/myfans-downloader:main
    build: .
    container_name: myfans-downloader
    environment:
      - CONFIG_DIR=/config
      - DOWNLOADS_DIR=/downloads
      - FILENAME_PATTERN={creator}_{date}_{title}
      - FILENAME_SEPARATOR=_
      - THREAD_COUNT=10
      - AUTH_TOKEN=your_token_here
      - LOG_FILE=/config/myfans_downloader.log
      - SEGMENT_DOWNLOAD_THREADS=15
      - WRITE_METADATA=0
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    user: 1000:1000
    cap_drop:
      - ALL
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"